- include_vars: install.yml
- name: モジュールインストール
  yum:
    name: '{{ item }}'
    enablerepo: remi,epel,rpmforge
    state: latest
  with_items: apache_items
- name: httpd起動
  service:
    name: httpd
    state: started
