- include_vars: configure.yml
- name: my.cnfの設置
  template:
    src: templates/my-small.cnf.j2
    dest: /etc/my.cnf
    group: root
    owner: root
    mode: 0644
    backup: yes
  notify: mysqlの起動
- name: .my.cnfファイルの確認
  stat: path=/root/.my.cnf
  register: mycnf_file
- name: MySQLのrootのパスワードの変更
  mysql_user:
    name: root
    host: '{{ item }}'
    password: '{{ root_db_password }}'
    login_user: root
    login_password: ''
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items: root_user_host
  when: mycnf_file.stat.exists == false
- name: .my.cnfにパスワード登録
  template:
    src: templates/python-my.cnf.j2
    dest: '/root/.my.cnf'
    owner: root
    group: root
    mode: 0600
- name: anonymousの削除
  mysql_user:
    name: ''
    state: absent
- name: test dbの削除
  mysql_db:
    name: test
    state: absent