#vagrant lamp環境設定
  - hosts: vagrant
    sudo: yes
    vars:
      root_db_password : password
    tasks:
       - name: yumファイルのkarnelをコメントアウト
         lineinfile:
           dest: /etc/yum.conf
           regexp: '^exclude='
           line: '#exclude=kernel*'
       - name: 時刻設定
         command: '\cp -f /usr/share/zoneinfo/Japan /etc/localtime'
       - name: 時刻設定ファイル書き換え
         lineinfile:
           dest: /etc/sysconfig/clock
           regexp: '^ZONE='
           line: 'ZONE="Asia/Tokyo"'
       - name: yum update実行
         yum:
           name: '*'
           state: latest
       - name: リポジトリ追加
         yum:
           name: '{{ item }}'
         with_items:
           - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
           - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
           - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
       - name: 一旦リポジトリ無効化
         replace:
           dest: '/etc/yum.repos.d/{{ item }}'
           regexp: 'enabled *= *1'
           replace: 'enabled=0'
         with_items:
           - epel.repo
           - rpmforge.repo
           - remi.repo
       - name: モジュールインストール
         yum:
           name: '{{ item }}'
           enablerepo: remi,epel,rpmforge
           state: latest
         with_items:
           - kernel-devel
           - kernel-headers
           - dkms
           - gcc
           - gcc-c++
           - httpd
           - httpd-devel
           - php
           - php-devel
           - php-pear
           - php-mbstring
           - php-mysql
           - mysql-server
           - mysql-devel
           - MySQL-python
       - name: vboxリビルド
         command: '/etc/init.d/vboxadd setup'
       - name: httpd.confのバックアップ
         command: 'cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.org'
         args:
           creates: /etc/httpd/conf/httpd.conf.org
       - name: httpd.confの設置
         template:
           src: templates/httpd.conf.j2
           dest: /etc/httpd/conf/httpd.conf
           group: root
           owner: root
           mode: 0644
           backup: yes
       - name: v_host.confの設置
         template:
           src: templates/v_host.conf
           dest: /etc/httpd/conf.d/v_host.conf
           group: root
           owner: root
           mode: 0644
       - name: httpd再起動
         service:
           name: httpd
           enabled: yes
           state: restarted
       - name: my.cnfの設置
         template:
           src: templates/my-small.cnf.j2
           dest: /etc/my.cnf
           group: root
           owner: root
           mode: 0644
           backup: yes
       - name: mysqlの起動
         service:
           name: mysqld
           enabled: yes
           state: started
       - name: .my.cnfファイルの確認
         stat:
          path=/root/.my.cnf
         register: mycnf_file
       - name: MySQLのrootのパスワードの変更
         mysql_user:
           name: root
           host: '{{ item }}'
           password: '{{ root_db_password }}'
           login_user: root
           login_password: ''
           check_implicit_admin: yes
           priv: "*.*:ALL,GRANT"
         with_items:
           - '127.0.0.1'
           - '::1'
           - 'localhost'
         when: mycnf_file.stat.exists == false
       - name: .my.cnfにパスワード登録
         template:
           src: templates/python-my.cnf.j2
           dest: '/root/.my.cnf'
           owner: root
           group: root
           mode: 0600
       - name: anonymousの削除
         mysql_user:
           name: ''
           state: absent
       - name: test dbの削除
         mysql_db:
           name: test
           state: absent
