#vagrant lamp環境設定
---
  - hosts: vagrant
    sudo: yes
    tasks:
       - name: yumファイルのkarnelをコメントアウト
         lineinfile:
          dest: /etc/yum.conf
          regexp: ^exclude=
          line: '#exclude=kernel*'
       - name: yum　update実行
         yum: name=* state=latest
       - name: リポジトリ追加
         yum: name={{item}}
         with_items:
          - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
          - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
          - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
       - name: 一旦リポジトリ無効化
         replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
         with_items:
          - epel.repo
          - rpmforge.repo
          - remi.repo